script: Fix make check
make check fails because cairo-script-private.h cannot be compiled
standalone:

./cairo-script-private.h:45:1: error: unknown type name ‘cairo_private’
...

./cairo-script-private.h:48:40: error: unknown type name ‘cairo_output_stream_t’